# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    "name": "Latam Documents",
    "version": "12.0.1.0.0",
    "author": "ADHOC SA",
    "category": "Localization",
    "depends": [
        "account",
        "base_validator",
    ],
    "data": [
        'views/account_journal_view.xml',
        'views/l10n_latam_account_journal_document_type_view.xml',
        'views/account_move_line_view.xml',
        'views/account_move_view.xml',
        'views/l10n_latam_document_type_view.xml',
        'views/account_invoice_view.xml',
        # 'views/res_company_view.xml',
        # 'views/res_partner_view.xml',
        # 'views/report_invoice.xml',
        # 'views/account_chart_template_view.xml',
        # 'views/account_payment_view.xml',
        # 'views/account_payment_receiptbook_view.xml',
        # 'views/menuitem.xml',
        # 'views/account_portal_templates.xml',
        # 'report/invoice_report_view.xml',
        # 'data/account.document.type.csv',
        # 'data/mail_template_invoice.xml',
        # 'wizards/account_invoice_refund_view.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
    ],
    'installable': True,
}
